insert into product (name, category, price) values ('What is Pivotal', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Java SE Advanced', 'Book', 1500);
insert into product (name, category, price) values ('Ace of Diamond', 'Comic', 450);
insert into product (name, category, price) values ('Apple iPhone 6S Black', 'Electronic', 78000);
insert into product (name, category, price) values ('Apple iPhone 6S Champagne Gold', 'Electronic', 78000);
insert into product (name, category, price) values ('Android Nexis 8', 'Electronic', 56000);
insert into product (name, category, price) values ('Apple iPad Pro', 'Electronic', 100000);
insert into product (name, category, price) values ('Apple iPad mini', 'Electronic', 45000);
insert into product (name, category, price) values ('Pivotal Cloud Foundry Immersion', 'Book', 2300);
insert into product (name, category, price) values ('Pivotal Cloud Foundry Advanced', 'Book', 1000);
insert into product (name, category, price) values ('Spring Cloud Services Overview', 'Book', 1500);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Nice Pingpong Table', 'House', 450000);
insert into product (name, category, price) values ('Pivotal HDB Introducation', 'Book', 1800);
insert into product (name, category, price) values ('Pivotal T-Shirts', 'Goods', 5500);
insert into product (name, category, price) values ('Pivotal Sticker', 'Goods', 120);
insert into product (name, category, price) values ('Pivotal Backpack', 'Goods', 7000);
insert into product (name, category, price) values ('Good Desk', 'Goods', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Microservice Architectures', 'Book', 1500);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Nice Pingpong table', 'House', 450000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
insert into product (name, category, price) values ('Good Desk', 'House', 150000);
