eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8081}}
  client:    # <--- ADD THE CLIENT SECTION!!!
    serviceUrl:
      defaultZone: ${vcap.services.springbox-service-registry.credentials.uri:http://scs-eureka-server-kaburt.cfapps.io}/eureka/
---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
